export enum ExchangeNamesEnum {
  binance = "binance",
}

export enum ConnectionTypesEnum {
  api = "api",
  wsApi = "wsApi",
  wsStream = "wsStream",
}

export enum RateLimitersEnum {
  REQUEST_WEIGHT = "REQUEST_WEIGHT",
  ORDERS = "ORDERS",
  RAW_REQUESTS = "RAW_REQUESTS",
}

export enum RateLimitIntervalsEnum {
  SECOND = "SECOND",
  MINUTE = "MINUTE",
  DAY = "DAY",
}

export enum FilterTypesEnum {
  PRICE_FILTER = "PRICE_FILTER",
  PERCENT_PRICE = "PERCENT_PRICE",
  LOT_SIZE = "LOT_SIZE",
  NOTIONAL = "NOTIONAL",
  ICEBERG_PARTS = "ICEBERG_PARTS",
  MARKET_LOT_SIZE = "MARKET_LOT_SIZE",
  MAX_NUM_ORDERS = "MAX_NUM_ORDERS",
  MAX_NUM_ALGO_ORDERS = "MAX_NUM_ALGO_ORDERS",
  MIN_NOTIONAL = "MIN_NOTIONAL",
}

export enum TradeSymbolStatusEnum {
  PRE_TRADING = "PRE_TRADING",
  TRADING = "TRADING",
  POST_TRADING = "POST_TRADING",
  END_OF_DAY = "END_OF_DAY",
  HALT = "HALT",
  AUCTION_MATCH = "AUCTION_MATCH",
  BREAK = "BREAK",
  ENABLED = "ENABLED",
}

export enum OrderTypesEnum {
  LIMIT = "LIMIT",
  MARKET = "MARKET",
  TAKE_PROFIT = "TAKE_PROFIT",

  STOP_LOSS_SPOT_ONLY = "STOP_LOSS",
  STOP_LOSS_LIMIT_SPOT_ONLY = "STOP_LOSS_LIMIT",
  TAKE_PROFIT_LIMIT_SPOT_ONLY = "TAKE_PROFIT_LIMIT",
  LIMIT_MAKER_SPOT_ONLY = "LIMIT_MAKER",

  TAKE_PROFIT_MARKET_FUTURES_ONLY = "TAKE_PROFIT_MARKET",
  TRAILING_STOP_MARKET_FUTURES_ONLY = "TRAILING_STOP_MARKET",
  STOP_FUTURES_ONLY = "STOP",
  STOP_MARKET_FUTURES_ONLY = "STOP_MARKET",
}

export enum TradePermissonEnum {
  SPOT = "SPOT",
  MARGIN = "MARGIN",
}
